/* Gate Runner: cosmetic only; it never changes SRS, XP, Gate Clear, or progress. */
(function () {
  'use strict';
  const LANES = 3, MAX_HEARTS = 3, COIN_KEY = 'lootlingua.runner.coins.v1', BEST_DISTANCE_KEY = 'lootlingua.runner.best-distance.v1';
  const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
  const shuffle = (items, random = Math.random) => { const out = items.slice(); for (let i = out.length - 1; i; i -= 1) { const j = Math.floor(random() * (i + 1)); [out[i], out[j]] = [out[j], out[i]]; } return out; };
  function normalizeWords(words) { const seen = new Set(); return (Array.isArray(words) ? words : []).map((x) => ({ word: String(x?.word || x?.term || '').trim(), meaning: String(x?.translation || x?.meaning || x?.ar || x?.definition || '').trim() })).filter((x) => x.word && x.meaning && !seen.has(`${x.word}\u0000${x.meaning}`) && seen.add(`${x.word}\u0000${x.meaning}`)); }
  function makeWordEvent(words, random = Math.random) { const pool = normalizeWords(words); if (pool.length < 3) return null; const prompt = pool[Math.floor(random() * pool.length)], other = shuffle(pool.filter((x) => x.meaning !== prompt.meaning), random).slice(0, 2); if (other.length < 2) return null; const options = shuffle([prompt, ...other], random).map((x) => x.meaning); return { word: prompt.word, options, correctLane: options.indexOf(prompt.meaning) }; }
  function calculateStage(width, height) { const w = Math.max(1, Number(width) || 1), h = Math.max(1, Number(height) || 1); return { width: w, height: h, scale: clamp(Math.min(w / 900, h / 520), .62, 1.35), compact: w < 560 || h < 520, portrait: h > w }; }
  function runnerPace(state) { return 1 + Math.min(.55, Math.floor(state.distance / 180) * .05); }
  function shouldDespawn(progress) { return Number(progress) > 1.08; }
  function createState(words) { return { words: normalizeWords(words), lane: 1, hearts: MAX_HEARTS, coins: 0, distance: 0, elapsed: 0, running: false, paused: false, over: false, event: null, feedback: null, nextEvent: 14500, eventUntil: 0, protectedUntil: 0, damageUntil: 0, lastInputAt: 0 }; }
  function step(state, delta, random = Math.random) { if (!state.running || state.paused || state.over) return state; const slowed = state.event || state.feedback, pace = runnerPace(state); state.elapsed += delta; state.distance += delta * .012 * pace * (slowed ? .58 : 1); if (!state.event && !state.feedback && state.elapsed >= state.nextEvent) { const event = makeWordEvent(state.words, random); if (event) { state.event = { ...event, phase: 'approach', readyAt: state.elapsed + 650 }; state.eventUntil = state.elapsed + 6500; } state.nextEvent += Math.max(10500, 15000 + Math.floor(random() * 6500) - Math.floor(state.distance / 60) * 180); } if (state.event?.phase === 'approach' && state.elapsed >= state.event.readyAt) state.event.phase = 'ready'; if (state.event && state.elapsed >= state.eventUntil) { state.event = null; state.protectedUntil = state.elapsed + 500; } if (state.feedback && state.elapsed >= state.feedback.until) state.feedback = null; return state; }
  function chooseLane(state, lane, at = performance.now()) { if (!state.running || state.paused || state.over || at - state.lastInputAt < 90) return { accepted: false }; state.lastInputAt = at; state.lane = clamp(lane, 0, LANES - 1); if (!state.event || state.event.phase !== 'ready') return { accepted: true, resolved: false, waiting: Boolean(state.event) }; const correct = state.event.correctLane === state.lane; state.event = null; state.feedback = { correct, lane: state.lane, until: state.elapsed + 850 }; state.protectedUntil = state.elapsed + 1250; if (!correct) { state.hearts -= 1; state.damageUntil = state.elapsed + 900; if (state.hearts <= 0) state.over = true; } return { accepted: true, resolved: true, correct }; }
  function addCoin(state, token) { if (!state.running || !token || token.collected) return false; token.collected = true; state.coins += 1; return true; }
  function hitObstacle(state, obstacle) { if (!state.running || !obstacle || obstacle.hit || state.damageUntil > state.elapsed || state.protectedUntil > state.elapsed) return false; obstacle.hit = true; state.hearts -= 1; state.damageUntil = state.elapsed + 900; if (state.hearts <= 0) state.over = true; return true; }
  function requestRunnerCloudSave() { if (window.auth?.currentUser && !window.__applyingCloudProfile) window.saveProfileToCloud?.(); }
  const RunnerCoinWallet = Object.freeze({ balance() { try { return Math.max(0, Number(localStorage.getItem(COIN_KEY)) || 0); } catch { return 0; } }, credit(amount) { try { localStorage.setItem(COIN_KEY, String(this.balance() + Math.max(0, amount))); requestRunnerCloudSave(); } catch {} } });
  const RunnerBestDistance = Object.freeze({ value() { try { return Math.max(0, Math.floor(Number(localStorage.getItem(BEST_DISTANCE_KEY)) || 0)); } catch { return 0; } }, save(distance) { const next = Math.max(0, Math.floor(Number(distance) || 0)); if (next <= this.value()) return false; try { localStorage.setItem(BEST_DISTANCE_KEY, String(next)); requestRunnerCloudSave(); } catch {} return true; } });
  function playRecordSound() { try { const Audio = window.AudioContext || window.webkitAudioContext; if (!Audio) return; const context = new Audio(); const oscillator = context.createOscillator(), gain = context.createGain(); oscillator.type = 'sine'; oscillator.frequency.setValueAtTime(660, context.currentTime); oscillator.frequency.exponentialRampToValueAtTime(880, context.currentTime + .14); gain.gain.setValueAtTime(.0001, context.currentTime); gain.gain.exponentialRampToValueAtTime(.035, context.currentTime + .018); gain.gain.exponentialRampToValueAtTime(.0001, context.currentTime + .22); oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + .23); oscillator.addEventListener('ended', () => context.close?.()); } catch {} }
  const node = (tag, cls, text) => { const el = document.createElement(tag); if (cls) el.className = cls; if (text != null) el.textContent = text; return el; };
  function render(context) { const card = node('aside', 'gate-runner-card'), copy = node('div', 'gate-runner-card-copy'); copy.append(node('strong', '', 'Runner'), node('span', '', 'اركض، تفادَ العوائق، واجمع العملات. عند التقاطع اختر معنى كلمة من البوابة.'), node('small', 'gate-runner-cosmetic', `🪙 العملات: ${RunnerCoinWallet.balance()} · 🏁 رقمك القياسي: ${RunnerBestDistance.value()}م`)); const play = node('button', 'gate-runner-launch', 'ابدأ Runner'); play.type = 'button'; play.addEventListener('click', () => launch(context)); card.append(copy, play); return card; }
  async function getWords(context) { const api = window.LootLinguaPublishedContent; return api?.listAllPublishedGateWords ? normalizeWords(await api.listAllPublishedGateWords(context.worldId, context.rankId, context.gateId)) : []; }
  function world() { const result = node('div', 'runner-world'); ['runner-skyline', 'runner-hills', 'runner-arches', 'runner-scenery runner-scenery-left', 'runner-scenery runner-scenery-right', 'runner-lights'].forEach((cls) => result.append(node('div', cls))); return result; }
  async function launch(context) {
    let words; try { words = await getWords(context); } catch { words = []; }
    const overlay = node('div', 'runner-overlay'), game = node('section', 'runner-game'); game.setAttribute('role', 'dialog'); game.setAttribute('aria-label', 'Runner');
    const header = node('header', 'runner-header'), hud = node('div', 'runner-hud'), hearts = node('span', 'runner-hud-hearts'), coins = node('span', 'runner-hud-coins'), distance = node('span', 'runner-hud-distance'); hud.append(hearts, coins, distance);
    const pause = node('button', 'runner-icon-button', '⏸ إيقاف'), exit = node('button', 'runner-exit', '× خروج'); pause.type = exit.type = 'button'; header.append(hud, pause, exit);
    const stage = node('div', 'runner-stage'); stage.tabIndex = 0; stage.append(world()); const tracks = node('div', 'runner-tracks'), player = node('div', 'runner-player'); tracks.append(player); stage.append(tracks); const prompt = node('div', 'runner-word-event'), signs = node('div', 'runner-lane-signs'); stage.append(prompt, signs);
    const controls = node('div', 'runner-controls'); [['يسار', 0], ['وسط', 1], ['يمين', 2]].forEach(([label, lane]) => { const button = node('button', 'runner-control', label); button.type = 'button'; button.dataset.lane = String(lane); controls.append(button); }); game.append(header, stage, controls); overlay.append(game); document.body.append(overlay);
    const state = createState(words), objects = []; state.running = true; let raf = 0, previous = performance.now(), spawnAt = 0, saved = false, destroyed = false, touchStart = null, feedbackTimer = 0, recordAnnounced = false, startingBest = RunnerBestDistance.value();
    const resize = () => { const size = calculateStage(stage.clientWidth, stage.clientHeight); game.classList.toggle('is-compact', size.compact); game.style.setProperty('--runner-scale', String(size.scale)); }, observer = typeof ResizeObserver === 'function' ? new ResizeObserver(resize) : null; observer?.observe(stage); resize();
    const cleanup = () => { if (destroyed) return; destroyed = true; cancelAnimationFrame(raf); clearTimeout(feedbackTimer); observer?.disconnect(); window.removeEventListener('keydown', keyboard); document.removeEventListener('visibilitychange', visibility); overlay.remove(); };
    const showSigns = (options, feedback) => { signs.replaceChildren(); (options || []).forEach((label, lane) => { const cls = `runner-lane-sign lane-${lane}${feedback?.lane === lane ? (feedback.correct ? ' is-correct' : ' is-wrong') : ''}`; const sign = node('div', cls, label); if (feedback?.lane === lane) sign.append(node('b', 'runner-choice-mark', feedback.correct ? '✓' : '×')); signs.append(sign); }); };
    const finish = (reason) => { if (saved) return; saved = true; state.running = false; RunnerCoinWallet.credit(state.coins); game.classList.add('is-finished'); signs.replaceChildren(); prompt.replaceChildren(node('strong', '', reason), node('span', '', `المسافة ${Math.floor(state.distance)} م · العملات ${state.coins}`)); const retry = node('button', 'runner-primary', 'إعادة اللعب'), leave = node('button', 'runner-secondary', 'العودة إلى البوابة'); retry.type = leave.type = 'button'; retry.addEventListener('click', (e) => { e.preventDefault(); e.stopPropagation(); cleanup(); void launch(context); }, { once: true }); leave.addEventListener('click', (e) => { e.preventDefault(); e.stopPropagation(); cleanup(); }, { once: true }); prompt.append(retry, leave); };
    const update = () => { const feedback = state.feedback, currentDistance = Math.floor(state.distance); if (!recordAnnounced && currentDistance > startingBest && RunnerBestDistance.save(currentDistance)) { recordAnnounced = true; window.showToast?.(`🏁 رقم قياسي جديد: ${currentDistance}م`, 'success', 3200); playRecordSound(); } game.classList.toggle('is-paused', state.paused); game.classList.toggle('is-damaged', state.damageUntil > state.elapsed); game.classList.toggle('is-word-event', Boolean(state.event)); game.classList.toggle('is-event-ready', state.event?.phase === 'ready'); game.classList.toggle('is-protected', state.protectedUntil > state.elapsed); player.style.setProperty('--lane', state.lane); hearts.textContent = `❤️ ${state.hearts} / ${MAX_HEARTS}`; coins.textContent = `🪙 ${state.coins}`; distance.textContent = `📏 ${currentDistance}م`; pause.textContent = state.paused ? '▶ متابعة' : '⏸ إيقاف'; if (game.classList.contains('is-finished')) return; prompt.replaceChildren(); if (state.event) { prompt.append(node('span', 'runner-event-kicker', state.event.phase === 'ready' ? 'تقاطع معنى — اختر الآن' : 'تقاطع قادم'), node('strong', '', state.event.word), node('span', 'runner-event-instruction', state.event.phase === 'ready' ? 'اختر المعنى عبر المسار المناسب' : 'استعد لقراءة المسارات')); showSigns(state.event.options); } else if (feedback) { prompt.append(node('strong', '', feedback.correct ? 'إجابة صحيحة ✓' : 'اختيار خاطئ — خسرت قلبًا'), node('span', '', feedback.correct ? 'انطلق!' : 'تابع، ما زالت لديك فرصة')); showSigns(feedback.options, feedback); } else showSigns(); };
    const select = (lane) => { const event = state.event, result = chooseLane(state, lane); if (!result.accepted) return; if (result.resolved) { state.feedback.options = event.options; game.classList.toggle('is-correct', result.correct); clearTimeout(feedbackTimer); feedbackTimer = setTimeout(() => { game.classList.remove('is-correct'); update(); }, 860); } update(); };
    const keyboard = (e) => { if (e.key === 'ArrowLeft' || e.key.toLowerCase() === 'a') { e.preventDefault(); select(state.lane - 1); } if (e.key === 'ArrowRight' || e.key.toLowerCase() === 'd') { e.preventDefault(); select(state.lane + 1); } if (e.key === 'Escape') cleanup(); }, visibility = () => { if (document.hidden && state.running && !state.over) { state.paused = true; update(); } };
    window.addEventListener('keydown', keyboard); document.addEventListener('visibilitychange', visibility); controls.addEventListener('pointerdown', (e) => { const button = e.target.closest('button[data-lane]'); if (button) { e.preventDefault(); select(Number(button.dataset.lane)); } }); stage.addEventListener('pointerdown', (e) => { touchStart = e.clientX; stage.setPointerCapture?.(e.pointerId); }); stage.addEventListener('pointerup', (e) => { if (touchStart == null) return; const delta = e.clientX - touchStart; touchStart = null; if (Math.abs(delta) > 24) select(state.lane + (delta > 0 ? 1 : -1)); }); pause.addEventListener('click', () => { if (!state.over) { state.paused = !state.paused; update(); } }); exit.addEventListener('click', cleanup);
    const spawn = () => { const protectedMoment = state.event || state.feedback || state.protectedUntil > state.elapsed, coin = protectedMoment || Math.random() < .64, lane = Math.floor(Math.random() * LANES); const item = node('div', coin ? 'runner-object is-coin' : `runner-object is-obstacle${Math.random() < .5 ? ' is-barrier' : ''}`); item.style.setProperty('--lane', lane); tracks.append(item); objects.push({ node: item, lane, coin, progress: 0, hit: false, collected: false }); };
    const retireOffscreenObjects = () => { for (let index = objects.length - 1; index >= 0; index -= 1) { const item = objects[index]; if (!shouldDespawn(item.progress)) continue; item.node.remove(); objects.splice(index, 1); } };
    function frame(now) { if (destroyed) return; const delta = Math.min(50, now - previous); previous = now; step(state, delta); const slowed = state.event || state.feedback ? .5 : 1, pace = runnerPace(state); if (state.running && !state.paused && now >= spawnAt) { spawn(); spawnAt = now + Math.max(460, 1100 - state.elapsed / 130 - Math.floor(state.distance / 80) * 18); } if (!state.paused) { objects.forEach((item) => { item.progress += delta * .00042 * pace * slowed; item.node.style.setProperty('--p', item.progress); if (item.progress > .82 && item.progress < 1.02 && item.lane === state.lane) { if (item.coin) { if (addCoin(state, item)) { item.node.classList.add('is-collected'); game.classList.add('is-coin-pickup'); setTimeout(() => game.classList.remove('is-coin-pickup'), 180); } } else if (hitObstacle(state, item)) item.node.classList.add('is-hit'); } }); retireOffscreenObjects(); } update(); if (state.over) finish('انتهت القلوب'); else raf = requestAnimationFrame(frame); }
    update(); stage.focus({ preventScroll: true }); raf = requestAnimationFrame(frame);
  }
  window.LootLinguaGateRunner = { render, normalizeWords, makeWordEvent, calculateStage, createState, step, chooseLane, addCoin, hitObstacle, runnerPace, shouldDespawn, RunnerCoinWallet, RunnerBestDistance, MAX_HEARTS };
})();
